### ISSUE TITLE
setupLayouts function hangs vite build

### ISSUE THREAD

**Issue by alexdeia** [JohnCampionJr/vite-plugin-vue-layouts#117] opened 2023-08-25 10:01 UTC
Hello guys.
Starting with vue 3.3 version, Vite build hangs when using setupLayouts function.
I wasted a lot of time but I didn't find out the reason of that behaviour.

Example:

**router/index.ts**
```typescript
import { setupLayouts } from 'virtual:generated-layouts'

// -- if using routes
import generatedRoutes from 'virtual:generated-pages'
// ---
...

const router = createRouter({
  extendRoutes: routes => setupLayouts(routes),

  // the same behavior
  routes: setupLayouts(generatedRoutes)
})
```

Summary: 

because of using setupLayouts vite build just hangs after these lines:

```bash
> vite build

vite v4.4.9 building for production...
✓ 927 modules transformed.
```

vite debug mode doesn't show anything interesting. Maybe someone faced this problem?

**Comment by valdoryu** [comment] 2023-10-20 14:25
Quickfix for everyone using vite-plugin-pages along with this plugin:

https://stackoverflow.com/questions/76281771/vite-build-command-hangs-at-modules-transformed-in-vue-3-3-4-vite-4-3-8-envi

However, if you are not using vite-plugin-pages, unplugin-vue-router should not be used as using extendRoutes for declarative routes is breaking router-link "to" props typings.

**Comment by alexdeia** [comment] 2023-10-23 05:49
Unfortunately, I later discovered another issues with that quick fix. Currently I have no ideas

**Comment by valdoryu** [comment] 2023-11-03 12:52
Up

**Comment by valdoryu** [comment] 2023-11-03 12:54
Up @JohnCampionJr 

Do you need a repro ?

**Comment by JohnCampionJr** [comment] 2023-12-05 00:00
I'm going to close this pending a repro; I can't duplicate and Vite is on to 5.0; if this persists there I will take another look.

**Closed by JohnCampionJr** 2023-12-05 00:00 UTC

**Comment by valdoryu** [comment] 2024-01-08 15:37
Hey, I know this issue is closed, I just wanted to say that with Vite 5.0, the issue unfortunately remains.
Maybe I can help you duplicate by giving you access to an emptied version of my app ?

**Comment by markthree** [comment] 2024-01-09 03:57
I'm sorry I can't reproduce the issue locally for me, if someone would like to provide a minimal reproduction repo I think I can see if I can fix the issue!

**Comment by valdoryu** [comment] 2024-01-09 13:45
I pinned down the issue to be with the presence of some JSX in a sub component used in one of my layout
Produced JSX is valid tho
I will deepen my search

Is there some limitations in layout plugin with JSX ?

**Comment by JohnCampionJr** [comment] 2024-01-09 19:33
Not that I know of, but I don't use JSX either....

**Comment by alexdeia** [comment] 2024-01-09 19:53
In my case the problem was the **defineAsyncComponent**, like

```javascript
const DefaultLayoutWithVerticalNav = defineAsyncComponent(() => import('./components/DefaultLayoutWithVerticalNav.vue'))
```

If you replace this code with a common synchronous import, the build will work fine. I never did find out why.

See details: https://stackoverflow.com/a/77616321/7014645
