### ISSUE TITLE
Routing nesting problem

### ISSUE THREAD

**Issue by AK47HaiJun** [JohnCampionJr/vite-plugin-vue-layouts#133] opened 2023-12-16 15:32 UTC
The first time I used this plugin,I have a route nesting problem, my route directory is correct, but the generated routes are not nested, and I also specify the default layout。
```js
import { createApp } from 'vue'
import App from './App.vue'
import { createHead } from '@vueuse/head'
import 'ant-design-vue/dist/reset.css';
import Antd from 'ant-design-vue';
import { createRouter, createWebHistory } from 'vue-router';
import generatedRoutes from 'virtual:generated-pages';
import { setupLayouts } from 'virtual:generated-layouts'



const routes = setupLayouts(generatedRoutes);

const router = createRouter({
  history: createWebHistory(),
  routes,
});

const head = createHead()


const app = createApp(App);
app.use(router);
app.use(Antd)
app.use(head)
app.mount('#app');
```

I also specified the layout. But I still can't. Look at the issues that my friend used. I tried it and it didn't work.
```js
<route lang="yaml">
    meta:
      layout: default
</route>
```

<img width="1010" alt="image" src="https://github.com/JohnCampionJr/vite-plugin-vue-layouts/assets/44810211/b76dfa9d-8513-41ed-81b9-3f83ac22f138">

How can I fix this, author  **thank you**

**Comment by JohnCampionJr** [comment] 2023-12-16 15:36
Duplicate of #130

**Closed by JohnCampionJr** 2023-12-16 15:36 UTC

**Comment by AK47HaiJun** [comment] 2023-12-17 09:00
My problem is still unresolved 
My directory structure is
<img width="345" alt="image" src="https://github.com/JohnCampionJr/vite-plugin-vue-layouts/assets/44810211/33f70c7e-d4fc-4cb2-a766-406e4cfa8023">
But the generated routing structure is wrong
I looked at #30 and it didn't solve my problem, and I updated it to 10 and it didn't solve my problem
<img width="991" alt="image" src="https://github.com/JohnCampionJr/vite-plugin-vue-layouts/assets/44810211/3e3b3f3c-fb60-4372-8bdb-ecf6fc63c8e5">
How to deal with it, thank you, author
