### ISSUE TITLE
Why are ['node_modules', '**/__*__/*'] excluded by default?

### ISSUE THREAD

**Issue by layen-king** [JohnCampionJr/vite-plugin-vue-layouts#138] opened 2024-01-03 10:46 UTC
I have a folder _base that does not need to be excluded. What should I do?

**Comment by JohnCampionJr** [comment] 2024-01-04 19:34
`__*__` as an exclude should not match `_base`

If it does, please provide a repro.

**Comment by layen-king** [comment] 2024-01-05 06:18
``` typescript
import Layouts from 'vite-plugin-vue-layouts'

export function useLayouts() {
  return Layouts({
    layoutsDirs: 'src/_base/layouts',
    defaultLayout: 'Layout',
  })
}
```
Configuration cannot take effect.

**Comment by layen-king** [comment] 2024-01-08 05:51
```
 "vite": "^4.5.0",
"vite-plugin-vue-layouts": "^0.8.0",
```

nodejs version v18.16.0

**Comment by JohnCampionJr** [comment] 2024-01-08 16:02
Please ensure you're on latest version.  If so, need a full repro.  I don't think this has anything to do with the exclusion.

**Comment by markthree** [comment] 2024-01-09 07:07
@layen-king I'm sorry, I couldn't reproduce the problem in the latest version, maybe you update to the latest version and try it!

example repo ->  [vue-layout-demo](https://github.com/markthree/vue-layout-demo)

**Comment by layen-king** [comment] 2024-01-09 07:44
I'm Sorry, I confirmed that it is caused by other plug-ins. Please close it.

**Comment by markthree** [comment] 2024-01-09 07:54
> I'm Sorry, I confirmed that it is caused by other plug-ins. Please close it.

Thanks for the reply, I closed it

**Closed by markthree** 2024-01-09 07:54 UTC
