### ISSUE TITLE
HMR does not works when work with `unplugin-vue-router`

### ISSUE THREAD

**Issue by liuwilliamBUPT** [JohnCampionJr/vite-plugin-vue-layouts#147] opened 2024-02-21 13:56 UTC
reproduces: [vue-layout-demo](https://github.com/liuwilliamBUPT/vue-layout-demo)

I find when use `pagesDirs` or `layoutsDirs` options, the hmr will fail. 

After I checked the code, I find if one of the options set, `canEnableClientLayout` will return `false`.Then simple hmr will not be use. 

At this [line](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/blob/2d52c68ab0107e3e735cacc6c041acdce1239b2f/src/index.ts#L68), a watcher will listen dirs without `config.root` path prepended. So when hmr start, this will no module match the file name, and the page will not refresh.

I think this line may be changed to
```
watcher.add(layoutDirs)
```
And I've tested it, it work for the reproduce.

**Comment by markthree** [comment] 2024-02-22 01:11
duplicate of #142，Let's track #141

**Closed by markthree** 2024-02-22 01:11 UTC
